### ISSUE TITLE
Wrong flags definition in Piped development Contribute Guide

### ISSUE THREAD

**Issue by tnqv** [pipe-cd/pipe#1049]
**What happened**:
I was trying to follow this [guide](https://pipecd.dev/docs/contribution-guidelines/piped-development/) to set up pipecd on local machine. And running
```
bazelisk run --run_under="cd $PWD && " //cmd/piped:piped -- piped \
--use-fake-api-client=true \
--project-id=local-dev-project \
--piped-id=local-dev-piped \
--piped-key-file=.dev/piped.key \
--bin-dir=/tmp/piped-bin \
--config-file=.dev/dev-config.yaml
```
to start it but it raised `unknown flag:` for follow flags: `project-id`, `piped-id`, `piped-key-file`

I read the code from [this](https://github.com/pipe-cd/pipe/blob/master/pkg/app/piped/cmd/piped/piped.go#L73
) and figure out that maybe the documents is outdated. 

**What you expected to happen**:
- Start server successfully.

**How to reproduce it**:
- Run this command after forking the code.
```
bazelisk run --run_under="cd $PWD && " //cmd/piped:piped -- piped \
--use-fake-api-client=true \
--project-id=local-dev-project \
--piped-id=local-dev-piped \
--piped-key-file=.dev/piped.key \
--bin-dir=/tmp/piped-bin \
--config-file=.dev/dev-config.yaml
```
to star

**Environment**:
- `piped` version: v0.8.0
- `control-plane` version: 
- Others:

**Comment by nghialv** [comment]
@tnqv Thanks for your issue.

Nice catch! You are absolutely right.
Could you make a pull request to remove those flags?

https://github.com/pipe-cd/pipe/blob/master/docs/content/en/docs/contribution-guidelines/piped-development.md

**Comment by tnqv** [comment]
@nghialv Thanks for replying!!
Besides this, there is also 1 problem while setting up I want to discuss:

When come to step:
`A piped configuration file piped-config.yaml`
And in the command, document is writing as `--config-file=.dev/dev-config.yaml`
It's a little bit confusing so I think it's better to make it the same. And add the [example link](https://github.com/pipe-cd/pipe/blob/master/pkg/config/testdata/piped/piped-config.yaml) to it.
How do you think ?

**Comment by nghialv** [comment]
@tnqv 

> It's a little bit confusing so I think it's better to make it the same.

Yes, you are right. I am happy to see another PR to fix this.

> And add the example link to it.

Nice idea. But that file is just test data so it could be changed in the future.
So I think we can add a simple example of a configuration file like this to the docs.

https://pipecd.dev/docs/operator-manual/piped/installation/#installing-on-a-single-machine

Thank you.

**Comment by nghialv** [comment]
@tnqv Could you send a PR for what we said above?

**Comment by tnqv** [comment]
@nghialv Sorry for replying late :sweat_smile: I've got some busy stuffs.
I'll create PR for the above discussion, also taking some notes while setting up the development.
But sadly, I'm following this [guide](https://pipecd.dev/docs/contribution-guidelines/control-plane-development/) and got stuck, although the server log is showing successfully, when I come `localhost:9082`. It's showing some kind like this :crying_cat_face: 
![Screenshot from 2020-11-04 15-42-03](https://user-images.githubusercontent.com/23372024/98088814-86d53b80-1eb4-11eb-9a5d-658d42dc41a0.png)
