### ISSUE TITLE
Add a name field for piped

### ISSUE THREAD

**Issue by nghialv** [pipe-cd/pipe#1139]
**What would you like to be added**:

Currently, piped is recognized by its unique ID on the web and notifications.
It is hard to remember and recognize them.

**Why is this needed**:

**Comment by nakabonne** [comment]
@nghialv This name isn't what you're saying?
![image](https://user-images.githubusercontent.com/19730728/100192320-165e8f00-2f35-11eb-90f5-a10756f02b45.png)

**Comment by nghialv** [comment]
oops...
/close

**Comment by nakabonne** [comment]
lol
