### ISSUE TITLE
The version of the `helloworld image` written in Quickstart does not match the actual manifest

### ISSUE THREAD

**Issue by sanposhiho** [pipe-cd/pipe#1149]
**What happened**:

According to [QuickStart](https://pipecd.dev/docs/quickstart/), the version of the `helloworld image` in [kubernetes/canary/deployment.yaml L22](https://github.com/pipe-cd/examples/blob/master/kubernetes/canary/deployment.yaml#L22)  is v0.1.0, but in fact, v0.5.0 is correct.

**Comment by nakabonne** [comment]
@sanposhiho Thank you for the reporting! Such things are often overlooked, helped a lot.
Could you vary the examples to match the instruction mentioned in the document? You can do that by touching here: https://github.com/pipe-cd/pipe/tree/master/examples
