### ISSUE TITLE
Merge server and ops into pipecd component

### ISSUE THREAD

**Issue by nghialv** [pipe-cd/pipe#1184]
**What would you like to be added**:

Change to provide only one binary/image named as `pipecd`.
As you know, currently we are having 4 cmds: `server`, `piped`, `ops`, `helloworld`.
Therefore for every commit, 4 binaries/container-images are produced.

In addition, we are also investigating to provide a new CLI tool, that causes a new cmd/binary/image.

So I propose to unify all of the things to a single cmd, single binary, single container image.
In order to start a thing:

```
pipecd server --
pipecd piped --
pipecd ops --
pipecd cli --
```

Good points:
- Simple (usage, CI, binary distributing...)

Bad points:
- The size of the binary will be larger. As I checked the size will be increased by 35% compared to `piped`.

**Why is this needed**:

**Comment by nghialv** [comment]
And this change does not cause any Breaking Changes.

**Comment by nakabonne** [comment]
Looks good proposal, but even we integrate the binaries, eventually the docker images will be separate, right?

**Comment by nghialv** [comment]
No, the docker images will be merged too.

**Comment by nghialv** [comment]
I mean they can be configured to be separate but should do? I was thinking about merging both binary and image.

**Comment by nakabonne** [comment]
I see, so far there seems to be no problem, but I'm worried about Piped's portability will be compromised.

**Comment by nakabonne** [comment]
I have doubts about including tools in the docker image that are not necessary for piped.

**Comment by nakabonne** [comment]
I agree with integrating things that always run at the same time, such as the server and ops, but I feel that each one performed in a different environment is better to be independent, but what do you think?

**Comment by nghialv** [comment]
Nice catch! 
You are right. Piped has a bunch of pre-installed tools inside its base image.

So we have these options:

Option 1. 2 groups:
- piped
- pipecd: server, ops, cli

Option 2. 3 groups:
- piped
- pipecd: server, ops
- cli

Option 3. no changes
- piped
- server
- ops
- cli

**Comment by nakabonne** [comment]
It seems a bit strange to integrate programs that run as daemons and those that don't, so `2` looks good. And how about `pipectl` for the cli name.

**Comment by nghialv** [comment]
Nice name. I have the same thought. Let's pick that solution.

```
- piped
- pipecd: server, ops
- pipectl
```

**Comment by nakabonne** [comment]
Looks neat 👍

**Comment by nakabonne** [comment]
Maybe the title should be varied.

**Comment by nghialv** [comment]
Right.
