### ISSUE TITLE
Automatically recreate piped pods when executing `helm upgrade` to update a piped configuration

### ISSUE THREAD

**Issue by mura-s** [pipe-cd/pipe#1216]
**What would you like to be added**:

When I change a piped configuration and execute `helm upgrade`, for now I have to manually restart piped pods to reflect the change. But It would be better that piped pods are automatically recreated.

ref: https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments

**Why is this needed**:

**Comment by nghialv** [comment]
@mura-s Thanks for your issue. You are absolutely right.
