### ISSUE TITLE
Enable to sync latest repo when being force pushed

### ISSUE THREAD

**Issue by nakabonne** [pipe-cd/pipe#128]
**What would you like to be added**:
It currently has no way to re-sync the latest commit history after the repository is force updated. We need to provider two features like:
- Show clear messages what's happened
- A way to refresh commit history of the repo

**Why is this needed**:
It would be important to provide options for repair while telling them that it's abnormal.

**Comment by nghialv** [comment]
Be a part of #1165 
/close
