### ISSUE TITLE
Improve insight collector

### ISSUE THREAD

**Issue by nghialv** [pipe-cd/pipe#1314]
Thanks @sanposhiho for his great job to bring the Insight feature to reality.

In the next phase, we want to improve this feature before releasing it.

### Current logic
- Get the list of all applications from the database
- Loop the applications
     - load chunk data from filestore
     - determine the `accumulatedTo` from the chunk data
     - retrieve all deployments created (or completed for FAILURE_RATE) from the the `accumulatedTo` to now
     - update the chunk data and store it back to filestore

### New logic

Add an `InsightMilestone` model to `datastore` to save a single`accumulatedTo` value for all projects. e.g.

``` golang
type InsightMilestone struct {
    DeploymentCreatedAtMilestone int64   // Mark that our collector has handled all deployment that was created before this value
    DeploymentCompletedAtMilestone int64 // Mark that our collector has handled all deployment that was completed before this value. This will be used while calculating FAILURE_RATE.
}
```

- Load the InsightMilestone to know the `milestone` value
- Retrieve all deployments created (or completed for FAILURE_RATE) after that `milestone`
- Grouping the deployments by project, application, etc...
- Load the needed chunk from filestore
- Update the chunk data and store it back to filestore
- Update the InsightMark and save it back to datastore

#### Pros
- Don't have to list all projects
- Don't have to list all applications
- Don't have to loop/retrieve all chunk of all applications in filestore (new logic only touches the applications that have at least one deployment triggered from the last calculation)
- Reduce the DB calls on deployment

#### Cons
-

**Comment by sanposhiho** [comment]
I think cons is that since the accumulatedTo is unified for the whole insight chunks, it is difficult to handle the case where even one chunk file fails to be saved for some reason.

In the current logic, there is an accumulatedTo for each file, so even if one file fails to be saved and is not updated, it will be updated next time. 
However, with the new logic, we'll have to come up with something clever.

**Comment by nghialv** [comment]
You are right. To be honest I was thinking about those cons. And I am thinking about these 2 solutions to remove those cons:
- the saving data should be idempotent. It means it is ok to re-apply (readd) the old data in case of error.
- using the `accumulatedTo` in each chunk to reject the already applied data

**Comment by sanposhiho** [comment]
I see.
Then the detailed flow in your idea is the following?

- Load the InsightMilestone to know the milestone value
- Retrieve all deployments created (or completed for FAILURE_RATE) after that milestone
- Grouping the deployments by project, application, etc...
- Load the needed chunk from filestore
- Update the chunk data 
  - **If chunk's accumulatedTo is not equal to InsightMark's DeploymentCreatedAtMilestone(or anothor), get deployments from DB after chunk's accumulatedTo. And Update the chunk data.**
- store  the chunk data back to filestore
- Update the InsightMark and save it back to datastore
