### ISSUE TITLE
Add support for FAKE image provider

### ISSUE THREAD

**Issue by nakabonne** [pipe-cd/pipe#1341]
**What would you like to be added**:
It would be nice to provide a FAKE image provider to deal with the rate limit from the container registry.

The FAKE container registry is deployed at the control-plane, and you can store the metadata about newly updated images whenever you want to (e.g. on your CI).

https://pipecd.dev/docs/operator-manual/piped/configuring-image-watcher/#fake

What we actually need:
- [x] New pipectl sub-command to upload the core of image manifest (repoName and tag are enough) by @nghialv 
- [x] gRPC API to store the manifest sent by the above command by @nghialv 
- [ ] Piped API to give back the latest tag so that the `FAKE` image provider works properly by @nakabonne 
- [ ] FAKE provider implementation that meets the `imageprovider.Provider` interface by @nakabonne

**Comment by nakabonne** [comment]
Just an idea, we may don't have to require users to install `pipectl` if we could implement [Docker Registry HTTP API V2](https://docs.docker.com/registry/spec/api):
```
docker login --username pipecd --password ${{ secrets.PIPECD_ACCESS_TOKEN }} https://PIPECD_SERVER_ADDRESS

docker push gcr.io/foo/bar:v0.1.0
```

Not sure it's possible to use different hosts between using when login and using when pushing, but I feel like it's worth adding to the future roadmap.

**Comment by nghialv** [comment]
It's a good idea to eliminate the dependency on pipectl.
Although there are some concerns about authentication and the complexity of the API,
but it looks interesting to dig deeper later.

**Comment by nakabonne** [comment]
No longer needed this issue due to https://github.com/pipe-cd/pipe/issues/1381
/close
