### ISSUE TITLE
Make it more clearly to display of enable/disable of application on the web

### ISSUE THREAD

**Issue by cakecatz** [pipe-cd/pipe#1360]
**What would you like to be added**:

**Why is this needed**:

- Update application list page design
- Update application detail page design
- Change the default value for the application filter

**Comment by cakecatz** [comment]
I created the list design.

![image](https://user-images.githubusercontent.com/6136383/103746839-0f06c700-5045-11eb-9965-3b18aa6f2d2f.png)

**Comment by nghialv** [comment]
@cakecatz I think most of the applications are enabled so I'm not sure that field should always be displayed like that.
Is there any other way like changing the background color, adding a badge for only disabled ones?

**Comment by cakecatz** [comment]
@nghialv 

If we follow the material design, it will look like this.
What do you think?

![image](https://user-images.githubusercontent.com/6136383/103855298-bfcc9f00-50f5-11eb-8a0b-4b9952ba5458.png)

**Comment by nghialv** [comment]
It looks like that row is not selectable. 😄  Can you update it in the Figma and we can talk at the MTG today?

**Comment by cakecatz** [comment]
@nghialv I updated Figma.

> we can talk at the MTG today?

Okay.

**Comment by cakecatz** [comment]
Finally, it was decided to change the background color.

![image](https://user-images.githubusercontent.com/6136383/103977291-519edf80-51bc-11eb-9472-eab72795dacc.png)

**Comment by nghialv** [comment]
Looks good. Thank you.
