### ISSUE TITLE
Make timeout of WAIT_APPROVAL stage configurable

### ISSUE THREAD

**Issue by nghialv** [pipe-cd/pipe#1371]
**What would you like to be added**:

Currently, there is no way to configure the timeout value for the WAIT_APPROVAL stage.

TODO:
- Adding the `timeout` field to configuration
  https://github.com/pipe-cd/pipe/blob/master/pkg/config/deployment.go#L222
- Returning an FAILURE status if the timed out
  https://github.com/pipe-cd/pipe/blob/master/pkg/app/piped/executor/waitapproval/waitapproval.go

**Why is this needed**:

**Comment by nakabonne** [comment]
Out of curiosity, does it automatically proceed if it passes the given timeout?

**Comment by nakabonne** [comment]
Ah, I've just followed the context. It ends with failure, right.
