### ISSUE TITLE
Let Ops automatically create Firestore composite indexes

### ISSUE THREAD

**Issue by nakabonne** [pipe-cd/pipe#1471]
**What would you like to be added**:
It would be nice if `pipectl` could automatically create needed composite indexes for Firestore. We have two options:

Ideally, we can implement the client for [firestore/v1](https://godoc.org/cloud.google.com/go/firestore), but seems like impossible. If we really can't, we should:

- execute `firebase deploy --only firestore:indexes` within pipectl
- execute `gcloud firestore indexes composite create` within pipectl
  - https://cloud.google.com/sdk/gcloud/reference/firestore/indexes/composite/create

**Why is this needed**:

**Comment by nakabonne** [comment]
Letting ops automatically update could be better.

With ops, we can get a couple of benefits:
- No longer needed to tell users how to create indexes
- We don't have to worry about dependency on particular commands including gcloud, firebase

Whereas, there are a few bit considerations.
- Whether we can really create indexes for the Firestore which has no documents

**Comment by nakabonne** [comment]
In case of firebase cli tool, users have to authenticate with one of two methods listed in descending priority:

- ***User Token***: provide an explicit long-lived Firebase user token generated from `firebase login:ci`. Note that these tokens are extremely sensitive long-lived credentials and are not the right option for most cases. Consider using service account authorization instead. The token can be set in one of two ways:
  - Set the `--token` flag on any command, for example firebase `--token="<token>"` projects:list.
  - Set the `FIREBASE_TOKEN` environment variable.

- ***Service Account***: set the `GOOGLE_APPLICATION_CREDENTIALS` environment variable to point to the path of a JSON service account key file.


Therefore, users have to give credentials to Ops to create composite indexes either way. So we have to tell users how to create indexes even if we choose ops. But ops still has a benefit to make the indexes upgrade easier. I'll keep up looking into them.

**Comment by nghialv** [comment]
> So we have to tell users how to create indexes even if we choose ops.

Can you explain more about this? I wonder why we have to?

In the case of using Ops, ServiceAccount looks good because Ops is already using Firestore's service account for its jobs.
One thing I want to confirm is that for creating composite indexes whether additional roles are required or not. If yes we have to update the docs here.
https://pipecd.dev/docs/operator-manual/control-plane/installation/#using-firestore-and-gcs

**Comment by nakabonne** [comment]
I haven't looked at ops in detail, so I assumed Ops and Server are explicitly distinguished. But if no, we don't have to worry about it.

**Comment by nakabonne** [comment]
(Sorry for interrupting you, it was just a note for the investigation log)

**Comment by nakabonne** [comment]
I just settled on letting Ops automatically create composite indexes using the `gcloud` command.

I choose Ops, not our pipectl because it turned out to be no problem to create indexes to the Firestore which has no Collections, no Documents.
And I choose the `gcloud` command, not the `firebase` command because simply I found it's impossible to create indexes for projects that aren't being integrated with the Firebase project.

If it will turn out that additional roles should be attached to the ServiceAccount, I'm going to append it to [the doc](https://pipecd.dev/docs/operator-manual/control-plane/installation/#using-firestore-and-gcs).

**Comment by nakabonne** [comment]
Using `gcloud` means simply repeate executing a kind of like this command:
```
gcloud firestore indexes composite create  --collection-group=Application  --field-config field-path=Deleted,order=ASCENDING  --field-config field-path=CreatedAt,order=ASCENDING
```

**Comment by nghialv** [comment]
👍  Let's do it.
