### ISSUE TITLE
Run a daemon process to automatically update indexes.json

### ISSUE THREAD

**Issue by nakabonne** [pipe-cd/pipe#1564]
**What would you like to be added**:
We need some kind of worker to keep [pkg/app/ops/firestoreindexensurer/indexes.json](https://github.com/pipe-cd/pipe/blob/master/pkg/app/ops/firestoreindexensurer/indexes.json) up-to-date. It basically does:
- periodically compare between our dev Firestore and indexes.json.
- Open a new PR

**Why is this needed**:
Currently, we have to manually update [pkg/app/ops/firestoreindexensurer/indexes.json](https://github.com/pipe-cd/pipe/blob/master/pkg/app/ops/firestoreindexensurer/indexes.json) whenever our Firestore composite indexes are updated.

It's likely to cause a `No Index Error` in a production environment someday.

**Comment by nghialv** [comment]
Nice.
But what does "daemon process" mean? And where it will be run?

**Comment by nakabonne** [comment]
Honestly, I don't have any explicit design yet, that's why I used such an abstract term. But I'm looking into some kind of tiny cli tool (explicitly different from pipectl, our own tool) which uses `pipe-cd/pipe/pkg/app/ops/firestoreindexensurer` as a library.

>And where it will be run?

I'm looking into running it inside our dev cluster. It's because this tool has to fetch indexes list from the Firestore.

**Comment by nakabonne** [comment]
We realized it isn't needed so much because we just need to change the workflow of updating indexes to only updating `indexes.json`.
/close
