### ISSUE TITLE
Stop dealing with "__name__" field

### ISSUE THREAD

**Issue by nakabonne** [pipe-cd/pipe#1578]
**What would you like to be added**:
Obviously, we don't have to pay attention to indexing to the `__name__` field which is automatically created by Firestore.
https://github.com/pipe-cd/pipe/blob/e2f5d788fd8cd414c03d76096d487e386ddf7d7d/pkg/app/ops/firestoreindexensurer/indexes.json#L17

Even without this `__name__` when Ops creates a new index, it creates it with an appropriate order.

However, we have to be sure to ignore this field when listing indexes to compare with defined-one (it's about `gcloud.listIndexes`).

**Why is this needed**:

**Comment by nghialv** [comment]
Nice.
