### ISSUE TITLE
Proposal: Add feature-flags in config to allow toggling the needed insights

### ISSUE THREAD

**Issue by sanposhiho** [pipe-cd/pipe#1582]
Hi team.

**Why is this needed**:

Currently, the ["enableInsightCollector-insight-collector"](https://github.com/pipe-cd/pipe/blob/aa9d0b8c8034fccd9894aa9778f7d6da5ba29cfb/cmd/pipecd/ops.go#L62) flag can be used to determine enable/disable all insights.

However,  there are several types of insights, and new insights are expected to be added in the future. 
And the user may want to disable only some insights.

**What would you like to be added**:

- create some fields in [ControlPlaneSpec](https://github.com/pipe-cd/pipe/blob/b16e7bd6e83e6124fb5616201a51995ec858c3f7/pkg/config/control_plane.go#L41), i.e., enable change failure rate, enable [application count](https://github.com/pipe-cd/pipe/issues/1436), etc.

**Comment by nghialv** [comment]
@sanposhiho Sorry for the late reply. (I had a long vacation. 🏂 )
Nice issue. I totally agree with you that we should provide fields/feature-flags inside that configuration block to allow enabling/disabling each kind of insight.

Happy to see your pull request to unlock that feature.
Thanks.
