### ISSUE TITLE
Unable to find out .pipe.yaml in the new application path

### ISSUE THREAD

**Issue by nakabonne** [pipe-cd/pipe#1595]
**What happened**:
I switched the application path from `playground/` to `playground-tmp/`, then do a quick sync.
Then looks like piped couldn't find out `.pipe.yaml`.

```
Unable to plan the deployment (error while preparing deploy source data (open /tmp/workspace061413939/f9fc56b1-2267-4af3-bbe9-92e0f394353d-planner-769907772/target-deploysource/deploysource240812651/repo/playground-tmp/.pipe.yaml: no such file or directory))
```

**What you expected to happen**:

**How to reproduce it**:

**Environment**:
- `piped` version:
- `control-plane` version:
- Others:

**Comment by nakabonne** [comment]
The reason is the directory created after `MostRecentSuccessfulCommitHash` cannot be read when getting running DSP.
https://github.com/pipe-cd/pipe/blob/6a5cf4389cd6209caf169968249988df7c3615a9/pkg/app/piped/planner/kubernetes/kubernetes.go#L156-L160

**Comment by nakabonne** [comment]
This issue happened because 

I spent a little bit of time solving it and found out the only way to solve this is letting `ApplicationDeploymentReference` the GitPath:

```diff
--- a/pkg/model/application.proto
+++ b/pkg/model/application.proto
message ApplicationDeploymentReference {
    string deployment_id = 1 [(validate.rules).string.min_len = 1];
    DeploymentTrigger trigger = 2 [(validate.rules).message.required = true];
    string summary = 3;
    string version = 4;
+   ApplicationGitPath git_path = 5 [(validate.rules).message.required = true];

    int64 started_at = 14 [(validate.rules).int64.gt = 0];
    int64 completed_at = 15 [(validate.rules).int64.gte = 0];
}
```

##### All changes can be shown through here: https://github.com/pipe-cd/pipe/commit/f215eb8bfa85610d4ce769241e8d121aa98109ac (maybe soon-to-be deleted)

But honestly, it's really odd because an ApplicationDeploymentReference has its own GitPath even though each Application has its own GitPath as well. And all components are assuming an Application has its own immutable Gitpath, and I believe it should keep it.
Besides,

**Comment by nghialv** [comment]
@nakabonne Nice. I totally agree with making GitPath immutable for each application.
So let's do it.

We will have 2 parts:
- Updating API to disallow changing the git path value
- @cakecatz Update application edit form to not allow updating that field

**Comment by nakabonne** [comment]
Right right. Okay, let me pick the first one. And I'm gonna open new issues for each.

**Comment by nakabonne** [comment]
Closing since both issues resolves this one.
/close
