### ISSUE TITLE
Unable to register data less than 3 rune

### ISSUE THREAD

**Issue by nakabonne** [pipe-cd/pipe#1732]
**What happened**:
I'm wanting to send `ab` as a Event watcher value:
```
pipectl event register --name=update-image --data=ab
```
But got:
```
invalid Event.Data: value length must be at least 3 runes
```

Looks validate for the data field is appropriate. I wonder why.

```proto
message RegisterEventRequest {
    string name = 1 [(validate.rules).string.min_len = 1];
    string data = 2 [(validate.rules).string.min_len = 1];
    map<string,string> labels = 3 [(validate.rules).map.keys.string.min_len = 1, (validate.rules).map.values.string.min_len = 1];
}
```
**What you expected to happen**:

**How to reproduce it**:

**Environment**:
- `piped` version:
- `control-plane` version:
- Others:

**Comment by nghialv** [comment]
Wrong value for validation in the model. lol
https://github.com/pipe-cd/pipe/blob/master/pkg/model/event.proto#L28

**Comment by nakabonne** [comment]
haha, no wonder!
