### ISSUE TITLE
Deployment is frozen on canceling while `WAIT` stage

### ISSUE THREAD

**Issue by khanhtc1202** [pipe-cd/pipe#1782]
**What happened**:

Config pipeline sync with `WAIT` stage then click `Cancel` while sync pipeline at stage `WAIT` causes unexpected state (deployment got freeze).

<img width="892" alt="Screen Shot 2021-03-26 at 0 20 07" src="https://user-images.githubusercontent.com/32532742/112497503-082c5c80-8dc9-11eb-81e8-9fa709ee8c4a.png">

Currently, I have to restart the piped agent to enable to rerun the deployment. The deployment will failure respectively but from the logs of piped `a command CancelDeployment is still not handled` errors log still exist.

**What you expected to happen**:

Enable to cancel pipeline sync on `WAIT` stage.

**How to reproduce it**:

**Environment**:
- `piped` version: 0.9.8
- `control-plane` version: 0.9.7
- Others:

**Comment by nakabonne** [comment]
Could be being unable to propagate the signal. But from skimming the code around the WAIT stage, apparently looks like it's handled well. I wonder why 🤔 
https://github.com/pipe-cd/pipe/blob/f5cdc8166025aa77a8a111245b9a65cc5ec495c6/pkg/app/piped/executor/wait/wait.go#L95-L104

**Comment by khanhtc1202** [comment]
It works normally if I increase the waiting time of `WAIT` stage 🤔 (30s in the below image)

<img width="893" alt="Screen Shot 2021-03-26 at 18 16 02" src="https://user-images.githubusercontent.com/32532742/112609855-63a92980-8e5f-11eb-90d2-9e18b5d6526e.png">

Looks like the problem has occurred when the `cancel` command is passed to the  control-plane but the handling side (piped) does not handle it well 👀

**Comment by khanhtc1202** [comment]
Piped log when bug is occurred

```
there are 1 planned/running deployments for scheduling	{"count": 1}
a command CancelDeployment was forwarded to its scheduler	{"app-id": "be769118-530d-405b-b1b3-f5fb6d59fff4", "deployment-id": "d1869b48-732e-4470-b80f-945e755d2410"}
stop scheduler because of temination signal	{"deployment-id": "d1869b48-732e-4470-b80f-945e755d2410", "app-id": "be769118-530d-405b-b1b3-f5fb6d59fff4", "env-id": "02e5c530-5100-4ae4-9913-fc98d351da45", "project-id": "pipecd", "app-kind": "LAMBDA", "working-dir": "/var/folders/0n/r_1ykvdj5vq092hj8qzt79d42q187t/T/workspace069945842/d1869b48-732e-4470-b80f-945e755d2410-scheduler-594506344", "stage-id": "stage-3"}
cleaning up working directory for scheduler	{"deployment-id": "d1869b48-732e-4470-b80f-945e755d2410", "app-id": "be769118-530d-405b-b1b3-f5fb6d59fff4", "working-dir": "/var/folders/0n/r_1ykvdj5vq092hj8qzt79d42q187t/T/workspace069945842/d1869b48-732e-4470-b80f-945e755d2410-scheduler-594506344"}
STAGE ERROR LOG: Failed to load lambda function manifest (open /var/folders/0n/r_1ykvdj5vq092hj8qzt79d42q187t/T/workspace069945842/d1869b48-732e-4470-b80f-945e755d2410-scheduler-594506344/target-deploysource/deploysource398462938/repo/lambda/canary/function.yaml: no such file or directory)	{"deployment-id": "d1869b48-732e-4470-b80f-945e755d2410", "stage-id": "stage-3"}

deleted done scheduler	{"deployment-id": "d1869b48-732e-4470-b80f-945e755d2410", "app-id": "be769118-530d-405b-b1b3-f5fb6d59fff4", "count": 1}
there are 1 planned/running deployments for scheduling	{"count": 0}
a command CancelDeployment is still not handled	{"app-id": "be769118-530d-405b-b1b3-f5fb6d59fff4", "deployment-id": "d1869b48-732e-4470-b80f-945e755d2410"}
```
