### ISSUE TITLE
Update piped Helm chart to make RBAC configurable

### ISSUE THREAD

**Issue by nghialv** [pipe-cd/pipe#1824]
**What would you like to be added**:

Currently, the kind and rules of RBAC for the `piped` chart are fixed as [here](https://github.com/pipe-cd/pipe/blob/master/manifests/piped/templates/rbac.yaml).

Some teams want to restrict the permissions of `piped` rather than the maximum list as the defaults.
So the chart should be fixed to
- make the following fields configurable:
  - kind: `ClusterRoleBinding`|`RoleBinding`, `ClusterRole`|`Role`
  - rules: `*` or the specified list

- allow configuring the piped deployment to use an external service account in case they don't want to create a new ServiceAccount
https://github.com/pipe-cd/pipe/blob/master/manifests/piped/templates/deployment.yaml#L22

**Why is this needed**:

**Comment by nakabonne** [comment]
@nghialv Hey, can I pick up this one?

**Comment by nghialv** [comment]
Sure. It is yours.
