### ISSUE TITLE
Do not inform non-namespaced resources when the namespace was specified

### ISSUE THREAD

**Issue by nghialv** [pipe-cd/pipe#1827]
**What happened**:

When the namespace was specified, there is no need to check the non-namespaced resources.
https://pipecd.dev/docs/operator-manual/piped/configuration-reference/#kubernetesappstateinformer
https://github.com/pipe-cd/pipe/blob/master/pkg/app/piped/livestatestore/kubernetes/reflector.go#L226

**What you expected to happen**:

**How to reproduce it**:

**Environment**:
- `piped` version:
- `control-plane` version:
- Others:

**Comment by nakabonne** [comment]
@nghialv This isn't directly related to https://github.com/pipe-cd/pipe/issues/1824 right? This namespace is [this](https://pipecd.dev/docs/operator-manual/piped/configuration-reference/#kubernetesappstateinformer) namespace, am I right?

**Comment by nghialv** [comment]
> This isn't directly related to #1824 right?
They are separate issues. But this is also needed to avoid error messages from piped.

> This namespace is this namespace, am I right?
Yes, that is.
