### ISSUE TITLE
Better use default cloud provider only when none

### ISSUE THREAD

**Issue by nakabonne** [pipe-cd/pipe#1836]
**What would you like to be added**:
I feel like it should be enabled only when no provider given because this default provider watch doesn't consider appStateInformer. That is, it surely starts watching for all namespace.
https://github.com/pipe-cd/pipe/blob/7066661a60df3269215c3e973237bf81715f2f90/pkg/config/piped.go#L101-L108
**Why is this needed**:

**Comment by nghialv** [comment]
To be honest, I was thinking about removing this default provider and forcing the user to specify it explicitly. (talked with @khanhtc before).

**Comment by nakabonne** [comment]
For sure. In that case, close this one and gonna open up a new one for it!
