### ISSUE TITLE
Ensure the Prometheus pod restarts at every version upgrade

### ISSUE THREAD

**Issue by nakabonne** [pipe-cd/pipe#1859]
**What would you like to be added**:
We need to reload Prometheus’ configuration whenever it makes any changes.

The only ways to reload configuration without restarting the process are:

- Sending signal: `kill -HUP 1234`
- Using reload API: `curl -X POST [http://localhost:9090/-/reload](http://localhost:9090/-/reload)`

One way to automatically update config using either of the above is making a sidecar that watches the Configmap changes and sends the signal to Prometheus process.

This way can prevent Prometheus from restarting, but a little bit tedious. We don't have to care about pod restarting because PipeCD rarely receives a high load. 

So looks better to ensure pod restart at every version upgrade.

**Why is this needed**:

**Comment by nakabonne** [comment]
The easiest way is just updating pods' annotations whenever upgrading helm chart. To do so, I hope we can dynamically template the replace version in `values.yaml` kind of like:

```yaml
prometheus:
  server:
    podAnnotations:
      app.kubernetes.io/version: {{ .Release .Name }}
```

But we can't.

**Comment by nghialv** [comment]
FYI, actually Prometheus loader is included in the chart.
https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/templates/server/deploy.yaml#L50

**Comment by nakabonne** [comment]
Right. We don't worry about the dynamical replacement anymore.
