### ISSUE TITLE
Create home directory for the user specified when deploying

### ISSUE THREAD

**Issue by nakabonne** [pipe-cd/pipe#1885]
**What would you like to be added**:
To enable to specify UID that Piped runs as, we granted write permission to `/etc/ssh/ssh_config` to all users on https://github.com/pipe-cd/pipe/pull/1880. But we're still running into a couple of issues for instance:
- a little bit insecure to grant write permission to `etc/ssh/ssh_config` to all users
- all anonymous users' home dir is `/`, so all operations that need a home directory doesn't work as well as we'd like:
```
2021/04/19 07:59:29 failed to add chart repository pipecd: Error: mkdir /.config: permission denied
```

We'd better seek out another way to do that.

**Why is this needed**:

**Comment by khanhtc1202** [comment]
> all operations that need a home directory doesn't work as well as we'd like

What a bad news 😞

**Comment by nakabonne** [comment]
This might sound like a silly idea, but another way we can do is:
- prepare a shared home dir like `/home/pipecd` that can be accessed by any other users.
- then, set that directory to all commands that try to read the home directory by default (e.g. `helm repo --registry-config=/home/pipecd`)

Hopefully, we can create a home dir for the user specified at `securityContext`, but if it can't then we're likely to look into it more.

**Comment by nakabonne** [comment]
All touched directory should be one owned by the logged-in user. Even if we grant permissions to a directory owned by root, this permission granting hell does not end.

```
failed to install kubectl	{"version": "1.18.10", "script": "\ncd /tmp/kubectl-install224539403\ncurl -LO https://storage.googleapis.com/kubernetes-release/release/v1.18.10/bin/linux/amd64/kubectl\nmv kubectl /tools/kubectl-1.18.10\nchmod +x /tools/kubectl-1.18.10\n\n", "out": "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100 42.0M  100 42.0M    0     0   113M      0 --:--:-- --:--:-- --:--:--  113M\nmv: can't rename 'kubectl': Permission denied\nchmod: /tools/kubectl-1.18.10: No such file or directory\n", "error": "exit status 1"}
```

**Comment by nakabonne** [comment]
Let me clear my thought
- Applications designed to expect a specific UID under which they will be running (like previous Piped) isn't good in terms of portability: https://www.openshift.com/blog/a-guide-to-openshift-and-uids
- Directories and files that may be written to by the Piped process should be owned by the logged-in user

**Comment by nakabonne** [comment]
Though I'm in the middle of https://github.com/pipe-cd/pipe/pull/1899, I'm facing a new issue. Running `git clone` with the Linux user not in `/etc/passwd` always fails, then emits `No user exists for uid 1000280000`.

**Comment by nakabonne** [comment]
The previous stuff is slightly different from the initial one. So I put it into https://github.com/pipe-cd/pipe/issues/1905.
