### ISSUE TITLE
"git clone" with the Linux user not in /etc/passwd fails

### ISSUE THREAD

**Issue by nakabonne** [pipe-cd/pipe#1905]
**What happened**:
Running git clone with the Linux user not in /etc/passwd always fails, then emits log a kind of like `No user exists for uid 1000280000`.

**What you expected to happen**:

**How to reproduce it**:

**Environment**:
- `piped` version:
- `control-plane` version:
- Others:

**Comment by nghialv** [comment]
😄  looks like we have to use `nss_wrapper` to resolve this problem for all OKD versions.
Ref: https://access.redhat.com/articles/4859371

**Comment by nakabonne** [comment]
There you go. That's what I was looking for!

**Comment by nakabonne** [comment]
>The OpenShift run-time CRI-O (starting from OpenShift 4.2 onward) now inserts the random user for the container into /etc/passwd. 

Well, anyway we don't have to care about OpenShift greater than 4.2.

Then, let's think about the case of using `nss_wrapper`. Sees like it just provides modifiable `/etc/passwd`, that means, eventually we have to set the entrypoint to execute scripts kind of like:
```bash
  export USER_ID=$(id -u)
  export GROUP_ID=$(id -g)
  grep -v -e ^default -e ^$USER_ID /etc/passwd > "$HOME/passwd"
  echo "default:x:${USER_ID}:${GROUP_ID}:Piped User:${HOME}:/sbin/nologin" >> "$HOME/passwd"
  export NSS_WRAPPER_PASSWD=${HOME}/passwd
  export NSS_WRAPPER_GROUP=/etc/group
```

**Comment by nakabonne** [comment]
hmm... I'm guessing running Piped with a user not in `/etc/passwd` could be thought extremely an edge case (almost only for those using OpenShift less than 4.1). One way to address this problem is executing a pre-defined script if the `--add-user-to-passwd` flag is given. Say, for example:
```
piped --add-user-to-passwd
```
In this case, Piped executes a script kind of like:
```bash
# Install nss_wrapper to add an random UID to "passwd" without having to directly modify /etc/passwd.
curl -L https://ftp.samba.org/pub/cwrap/nss_wrapper-1.1.11.tar.gz | tar xvz
mv nss_wrapper-1.1.11 {{ .BinDir }}/nss_wrapper
chmod +x {{ .BinDir }}/nss_wrapper

# Add login user to $HOME/passwd
export USER_ID=$(id -u)
export GROUP_ID=$(id -g)
grep -v -e ^default -e ^$USER_ID /etc/passwd > "$HOME/passwd"
echo "default:x:${USER_ID}:${GROUP_ID}:Piped User:${HOME}:/sbin/nologin" >> "$HOME/passwd"
export NSS_WRAPPER_PASSWD=${HOME}/passwd
export NSS_WRAPPER_GROUP=/etc/group
```

**Comment by nakabonne** [comment]
(Just a note: yesterday, we settled on installing nss_wrapper when building the Piped container, not at runtime)

Installing `nss_wrapper` on Alpine is a little bit tedious and I'm stuck with that. No package is distributed for apk, that means, we have to install nss_wrapper from source. `nss_wrapper` is a C library, not a simple single binary. That is, we need to put a couple of source files under `/usr/lib`. I made a guess by looking over where [nss_wrapper yum package](https://centos.pkgs.org/7/centos-sclo-rh-x86_64/nss_wrapper-1.0.3-1.el7.x86_64.rpm.html) and [Ubuntu's libnss_wrapper](https://packages.ubuntu.com/xenial/amd64/libnss-wrapper/filelist) place files.

According to [the installation instruction](https://git.samba.org/?p=nss_wrapper.git;a=blob;f=README.install;h=7ee4e714ab69c85591dacee8e115d93d764d29a4;hb=HEAD), we need to be done these step after downloading the source code.

```bash
BASE_URL="https://ftp.samba.org/pub/cwrap/nss_wrapper"
VERSION="1.1.11"

echo "Installing nss_wrapper-${VERSION}
curl -L ${BASE_URL}-${VERSION}.tar.gz | tar xvz

cd nss_wrapper-${VERSION}
export CC=`which clang`
cmake -DCMAKE_INSTALL_PREFIX=${VERSION}
cmake -DCMAKE_BUILD_TYPE=Release
make
make install
```

Obviously it causes a bunch of dependencies on its build system. One way to avoid them is using multi stage build but I'm wondering if we should do so much.

**Comment by nakabonne** [comment]
Hopefully we can install `nss_wrapper` without any need to build ourselves. I'll look up whether such a way exists, but if none of them would work, we have a couple of ways we can do. I'm still debating, which is better:
- Keep going to install nss_wrapper from source
- Look for other solutions other than nss_wrapper
- ...

**Comment by nakabonne** [comment]
Another solution that makes this problem clear but could be a bit insecure is; granting write permission of `/etc/passwd` to the root group (chmod 664 `/etc/passwd`) like [Jenkins did before OpenShift 4.2](https://github.com/openshift/jenkins/pull/1015/files#diff-9b81bb95baefc97d522d9f616ac3559243ab77b3a7f4882fb6768de2f8267d68). All containers run on OpenShift belong to the root group (GID=0), so it could work well.

**Comment by nakabonne** [comment]
But [OpenShift](https://access.redhat.com/articles/4859371) does recommend using `nss_wrapper`, gonna keep going to use that.

**Comment by nakabonne** [comment]
Another way is making a new piped-base image dedicated for OpenShift less than 4.1. We can build the image on top of CentOS-based OS which can get along with [cwrap](https://cwrap.org) including nss_wrapper. In this way we can prevent piped-base image from being too complicated but can be running into the maintenance cost issue.

**Comment by nakabonne** [comment]
Another way is to ask OpenShift users to prepare a piped-wrapped image that is for installation `nss_wrapper`.

**Comment by nghialv** [comment]
Let me take a look.

**Comment by nakabonne** [comment]
sorry, just commented what I'm thinking so forgive me that it doesn't keep clean and tidy.

**Comment by nghialv** [comment]
That is ok. Nice comments.

**Comment by nakabonne** [comment]
Let me organize the ideas:
- Building and installing `nss_wrapper` from source
- Looking for other ways to install `nss_wrapper` without building (almost surely nothing though)
- Looking into other solution other than `nss_wrapper` (OpenShift recommend using `nss_wrapper` so maybe none is suitable)
- making a new piped-base image dedicated for OpenShift less than 4.1.
- Ask OpenShift users to prepare a piped-wrapped image that is for installation nss_wrapper.

And I'm honestly stuck with even building `nss_wrapper` with gcc. It doesn't go as well as we'd like, emit a bunch of build errors. I'm in the middle of looking up why.

**Comment by nakabonne** [comment]
Another way with `nss_wrapper`, that doesn't include waste dependency within the piped image is, creating a CentOS-based container for preparing `nss_wrapper`. And it shares the value with the piped container. When initializing container, that executes a script like:

```bash
yum install nss_wrapper

export USER_ID=`id -u`
export GROUP_ID=`id -g`

cp /usr/lib64/libnss_wrapper.so ${SHARED_DIR}/libnss_wrapper.so
echo "piped-for-okd:x:${USER_ID}:${GROUP_ID}:Piped user:${USER_HOME}:/bin/bash" ${SHARED_DIR}/passwd
```

But there are some concerns. Alpine relies on glibc by default unlike CentOS. Seems like we can setup it with [alpine-pkg-glibc](https://github.com/sgerrand/alpine-pkg-glibc), but still doesn't work. Never mind.

**Comment by nghialv** [comment]
Looks like from git `2.6.5` (our current version is `2.6.2`), it is ok to run git clone when the user is not in /etc/passwd.
So can you try updating our git to the latest version and check again?

(One another way that could work is specifying name/email for Git to use instead of retrieving from /etc/passwd. But upgrading Git looks simpler.
)

**Comment by nakabonne** [comment]
What version actually git is `2.26.2`, but you have a point. It turns out it's enough to look for just a workaround for git. A permanent solution could be unneeded a while.

**Comment by nakabonne** [comment]
Not git client itself, seems like the ssh client emits "No user exists for uid xxx" transparently. The fact that git clone with `https` goes well makes it clear. Nonetheless, nothing isn't changed; I'm in the middle of looking for the workaround to perform SSH without `getpwuid()` to look for ident.

**Comment by nakabonne** [comment]
We can suppose that most of users of OpenShift <4.2 will bump it to more than 4.2. I settled on providing a temporary image dedicated to OpenShift <4.2. I'm looking into a couple of ways:
- Using `nss_wrapper`
  - Wrap the current alpine-based piped-base image. 
  - Build a brand new piped-base image based on CentOS that is suitable for installation `nss_wrapper`

- Just granting write permission of `/etc/passwd` to the root group (chmod 664 /etc/passwd)

**Comment by nakabonne** [comment]
I'd like to employ the first one, the way to use `nss_wrapper` on the alpine-based piped-base-okd image as possible to be honest. If impossible then switching to use CentOS as a base image looks alright.

**Comment by nakabonne** [comment]
I'm going to take four-stage approach:
- [ ] Prepare `piped-base-with-nss-wrapper` image
- [ ] Empower piped application to add the logged-in user to /etc/passwd when `--add-login-user-to-passwd` given
- [ ] Enable continuous pushing piped image based on `piped-base-with-nss-wrapper`.
- [ ] Allow helm chart to vary if it uses nss_wrapper or not using Helm values.
