### ISSUE TITLE
Events not committed by piped

### ISSUE THREAD

**Issue by m-ronchi** [pipe-cd/pipe#1934]
**What happened**: new events created with `pipectl event register ...` do not get committed in the repo.
logs from piped:
```
application 6e131a59-2ad8-4833-8db5-XXXXXXXXXXXX has 8 manifests at commit XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX     {"cloud-provider": "kubernetes-default"}
application 6e131a59-2ad8-4833-8db5-XXXXXXXXXXXX has 8 live manifests   {"cloud-provider": "kubernetes-default"}
application 7ccf2dd7-5611-49d6-b8a7-XXXXXXXXXXXX has 22 manifests at commit XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    {"cloud-provider": "kubernetes-default"}
application 7ccf2dd7-5611-49d6-b8a7-XXXXXXXXXXXX has 22 live manifests  {"cloud-provider": "kubernetes-default"}
application 57d1b58e-d3f3-4ea3-9415-XXXXXXXXXXXX has 5 manifests at commit XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX     {"cloud-provider": "kubernetes-default"}
application 57d1b58e-d3f3-4ea3-9415-XXXXXXXXXXXX has 5 live manifests   {"cloud-provider": "kubernetes-default"}
application 4c9266ac-0123-4403-b15c-XXXXXXXXXXXX has 15 manifests at commit XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    {"cloud-provider": "kubernetes-default"}
application 4c9266ac-0123-4403-b15c-XXXXXXXXXXXX has 15 live manifests  {"cloud-provider": "kubernetes-default"}
application 94b85dc8-fd08-4dfa-a065-XXXXXXXXXXXX has 27 manifests at commit XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    {"cloud-provider": "kubernetes-default"}
application 94b85dc8-fd08-4dfa-a065-XXXXXXXXXXXX has 27 live manifests  {"cloud-provider": "kubernetes-default"}
successfully collected and reported metrics     {"num": 39, "duration": 3.795058525}
given event not found   {"event-name": "image-update", "labels": {"app":"*****","env":"prod"}}
event watcher will update 3 outdated values
failed to update the values     {"repo-id": "*********", "error": "failed to perform git commit: failed to commit, branch: master, error: no change"}
github.com/pipe-cd/pipe/pkg/app/piped/eventwatcher.(*watcher).run
        pkg/app/piped/eventwatcher/eventwatcher.go:159
no update to sync for application, hash: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX       {"app": "*****", "app-id": "6e131a59-2ad8-4833-8db5-XXXXXXXXXXXX", "head-commit": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"}
no update to sync for application, hash: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX       {"app": "*****", "app-id": "7ccf2dd7-5611-49d6-b8a7-XXXXXXXXXXXX", "head-commit": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"}
no update to sync for application, hash: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX       {"app": "*****", "app-id": "57d1b58e-d3f3-4ea3-9415-XXXXXXXXXXXX", "head-commit": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"}
no update to sync for application, hash: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX       {"app": "*****", "app-id": "4c9266ac-0123-4403-b15c-XXXXXXXXXXXX", "head-commit": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"}
no update to sync for application, hash: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX       {"app": "*****", "app-id": "94b85dc8-fd08-4dfa-a065-XXXXXXXXXXXX", "head-commit": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"}
```

**Environment**:
- `piped` version: 0.9.9
- `control-plane` version: 0.9.9
- Others:

how do I even debug this?

**Comment by nakabonne** [comment]
@m-ronchi Hey, thank you for reporting this issue. It seems a little bit odd; git commit looks to be failed due to "error: no change". But typically it shouldn't try to do "git commit" when nothing to commit.

I gave it a shot to repro it but I couldn't sadly. Tell me a little bit more about what you did, how to repro it. For instance, what value did you try to replace? what command did you give it a try?

**Comment by m-ronchi** [comment]
I tried a bunch of different event values, but none appeared to work.
is it possible that there is an old event stuck in the queue that breaks the processing?
these logs ```given event not found   {"event-name": "image-update", "labels": {"app":"*****","env":"prod"}}
event watcher will update 3 outdated values``` are suspicious (the `event not found` refers to a different app that what I tried to update.

is there a way to fetch all registered events from the cli or frontend?

**Comment by nakabonne** [comment]
Log `given event not found` indicates just not found in control-plane; no matter different apps arent' registered, `git commit` shouldn't get stuck at all.

>is there a way to fetch all registered events from the cli or frontend?

The current only way to look at it is to directly inspect your datastore.

**Comment by nakabonne** [comment]
Within the message, the last part `no change` is the error log emitted by `git commit`. I've never seen such a log. I wonder what it means. Do you know that?

**Comment by m-ronchi** [comment]
I just found out that this piped instance did not update when we updated pipecd from 0.9.9.

updating and restarting resolved the issue

**Comment by m-ronchi** [comment]
Hi,
yesterday this exact error happened again.

I investigated, and it appears that it happens if there are more that 1 event applied at the same time:
- for each event, you write the files to disk [here](https://github.com/pipe-cd/pipe/blob/master/pkg/app/piped/eventwatcher/eventwatcher.go#L236)
- then you try to commit the changes for each event again ([here](https://github.com/pipe-cd/pipe/blob/master/pkg/app/piped/eventwatcher/eventwatcher.go#L201-L202)). first event commits all files, then any other event will fail because changes were already committed by the first event

**Comment by nakabonne** [comment]
@m-ronchi Hey, I could repro it as you reported initially. 
```
failed to update the values	{"repo-id": "delivery", "error": "failed to perform git commit: failed to commit, branch: master, error: no change"}
```

You're quite right. Seems like it happens if you would register multiple events during a single fetch interval. I will address it as on as possible. Thank you for finding out!

**Comment by nakabonne** [comment]
@m-ronchi Hey, the [v0.10.3](https://github.com/pipe-cd/pipe/releases/tag/v0.10.3) with this bug fix got out. Please check it out and give it a shot!
