### ISSUE TITLE
Dedicated type for datastore operator

### ISSUE THREAD

**Issue by nakabonne** [pipe-cd/pipe#2027]
**What would you like to be added**:
Currently, literal string is used where it queries to datastore. Sometimes we get confused like "which operators can we use?" I feel like it would be kind for newbies to clarify which operators are available like:

```go
type Operator string

const (
	OperatorEqual              Operator = "=="
	OperatorNotEqual           Operator = "!="
	OperatorIn                 Operator = "in"
	OperatorNotIn              Operator = "not-in"
	OperatorGreaterThan        Operator = ">"
	OperatorGreaterThanOrEqual Operator = ">="
	OperatorLessThan           Operator = "<"
	OperatorLessThanOrEqual    Operator = "<="
)
```

Use them instead of using literal string directly.

```go
		Filters: []datastore.ListFilter{
			{
				Field:    "ProjectId",
				Operator: datastore.OperatorEqual,
				Value:    claims.Role.ProjectId,
			},
		},
```

**Why is this needed**:

**Comment by nakabonne** [comment]
Truthfully, I look over here every time to confirm the valid operators 😂 :
https://github.com/pipe-cd/pipe/blob/49a30ff35039050f854229acb94d41b1fc461950/pkg/datastore/mysql/query.go#L204-L222

**Comment by khanhtc1202** [comment]
This would be nice 🤣

**Comment by nakabonne** [comment]
Thank you. If @nghialv also upvotes this idea, I'm going to get started with implementation right now.

**Comment by nghialv** [comment]
That is nice. Let's do it.

**Comment by nakabonne** [comment]
I will do it, do it!
