### ISSUE TITLE
Successfully text shown even though it fails to delete an environment

### ISSUE THREAD

**Issue by nakabonne** [pipe-cd/pipe#2036]
**What happened**:
As shown below, I could see a doubled popup that confused me.

![image](https://user-images.githubusercontent.com/19730728/120579009-b99edc80-c461-11eb-99aa-ab9e347e45a8.png)

**What you expected to happen**:

**How to reproduce it**:

**Environment**:
- `piped` version:
- `control-plane` version:
- Others:

**Comment by nakabonne** [comment]
@cakecatz Could you take a look?

**Comment by cakecatz** [comment]
@nakabonne Sure, I'll fix it!

**Comment by nakabonne** [comment]
Thank you!
