### ISSUE TITLE
Deleted environments are alive

### ISSUE THREAD

**Issue by nakabonne** [pipe-cd/pipe#2038]
**What happened**:
1, I could let Piped use deleted environments.

![image](https://user-images.githubusercontent.com/19730728/120590371-620a6c00-c475-11eb-8ee9-689c53e06ec1.png)

2, I could use deleted environment for flltering

![image](https://user-images.githubusercontent.com/19730728/120591965-f8d82800-c477-11eb-9950-4fd469fb9f88.png)

**What you expected to happen**:

**How to reproduce it**:

**Environment**:
- `piped` version:
- `control-plane` version:
- Others:

**Comment by khanhtc1202** [comment]
Looks like it comes from here 👀 
https://github.com/pipe-cd/pipe/blob/master/pkg/app/api/grpcapi/web_api.go#L154-L162

**Comment by nakabonne** [comment]
Right
