### ISSUE TITLE
Migrate Ingress API Versions from networking.k8s.io/v1beta1 to networking.k8s.io/v1

### ISSUE THREAD

**Issue by misukuro** [pipe-cd/pipe#2301]
**What would you like to be added**:

I'm using PipeCD to deploy the Ingress resource of the `networking.k8s.io/v1` API version.
The following error occurs, and the status of the PipeCD application does not become Healthy, but remains `Other`.
```
Health Description:
Unexpected error while calculating: unable to convert *unstructured.Unstructured to *v1beta1.Ingress: no kind "Ingress" is registered for version "networking.k8s.io/v1" in scheme "pkg/runtime/scheme.go:101"
```

I would like to see support for `networking.k8s.io/v1` API version for Ingress resources.

**Why is this needed**:

The `extensions/v1beta1` and `networking.k8s.io/v1beta1` API versions of Ingress will no longer be served in v1.22.
The Ingress resource needs to be migrated to `networking.k8s.io/v1` API version.

**Environment**:
- `piped` version: v0.11.1
- `control-plane` version: v0.11.1
- Others: k8s v1.19

**Comment by nghialv** [comment]
Thanks for your issue. You are right.

/assign @nakabonne

**Comment by nakabonne** [comment]
@misukuro Hi, this is resolved by https://github.com/pipe-cd/pipe/pull/2321. You will be able to use the fixed one from the next version.

**Comment by misukuro** [comment]
@nakabonne Thank you very much!
