### ISSUE TITLE
Unify the slack notification message for all kinds of event

### ISSUE THREAD

**Issue by khanhtc1202** [pipe-cd/pipe#2556]
**What would you like to be added**:

I think the current Slack notification message text is hard to understand and a bit weird. Besides, the text for different kinds of events may require mentioned names in the head or tail of the text to make it easier to understand, so I think we should unify the Slack message for all kinds of events by adding a new Slack field `Persons in charge` and keep the `text` field as is for all kinds. In that case, one thing that needs to confirm is ensuring that mentioned users will be noticed even if the name is in the Slack field (not the text field), what do you think?

note: 
1. by mentioned slack field, I mean this type [slackField](https://github.com/pipe-cd/pipe/blob/master/pkg/app/piped/notifier/slack.go#L236-L240)
2. In the below case, instead of using text `Approvable users: xxx`, I want to add a `Persons in charge` field to the message and make the same thing with messages of other event kinds.
<img width="656" alt="Screen Shot 2021-10-02 at 16 22 20" src="https://user-images.githubusercontent.com/32532742/135707913-155aca7c-64ee-49bd-aae2-587cfb843d88.png">

**Why is this needed**:

**Comment by ono-max** [comment]
It makes sense to me and I think it's no problem even if the `Persons in charge` field is empty. It may a good opportunity to show the mentioned user options.

**Comment by ono-max** [comment]
I'd like to discuss the field name because `Persons in charge` is clear for WAIT_APPROVAL event, but sounds weird for DEPLOYMENT_TRIGGERED event to me.

**Comment by khanhtc1202** [comment]
> I'd like to discuss the field name because `Persons in charge` is clear for WAIT_APPROVAL event, but sounds weird for DEPLOYMENT_TRIGGERED event to me.

Sure, which name do you prefer? I have some ideas: Persons in charge, Mention to, Watchers, Facilitators.

**Comment by ono-max** [comment]
I like Mention to. Do you agree with my opinion?

**Comment by khanhtc1202** [comment]
I don't have a strong opinion about that but it looks good since it shows that it is related to the `notification.mentions` field explicitly. How do you think? @nghialv @nakabonne

**Comment by nghialv** [comment]
I like the idea of moving them into a new field like the `Kind` field in the image.
About the name, it could be `Mentions`.

**Comment by nghialv** [comment]
Btw, I am not sure that mention can be included in the Slack field or not.

**Comment by nghialv** [comment]
https://github.com/pipe-cd/pipe/blob/master/pkg/app/piped/notifier/slack.go#L144-L151

**Comment by nakabonne** [comment]
> I like the idea of moving them into a new field like the Kind field in the image.
About the name, I vote for Mention To or Mentions.

I feel totally the same way.

**Comment by ono-max** [comment]
Thank you, guys.

> Btw, I am not sure that mention can be included in the Slack field or not.

Let me give it a try.
