### ISSUE TITLE
Empower Application form to suggest existing tags based on characters being typed

### ISSUE THREAD

**Issue by nakabonne** [pipe-cd/pipe#2710]
**What would you like to be added**:
Like other services, it's nice to enter multiple tags by delimiting them by spaces.

It would also be helpful if it could suggest existing tags based on characters being typed. But we don't have any search engine for Tags so it's a bit difficult to fuzzy search currently. But the number of tags is more likely to be less.
One way that we can apply to the current architecture is letting client fuzzy search, like:
- Store tags in Datastore (ProjectId, Tag)
- Fetch all tags related to the logged-in project when calling ListApplications
- The web client does fuzzy search when entering tags

Ideal:
![image](https://user-images.githubusercontent.com/19730728/139178693-c72a86a3-9ebf-48cc-94f2-9039413ceab3.png)

**Why is this needed**:

**Comment by nghialv** [comment]
This is exactly what happened to the Environment model. Firstly, we thought that the environment ID should be some kind of "ProjectName + EnvName" for easy handling. But after all, it turned to be a UUID and the EnvName is just some kind of "display" name to make it easy to update the name.

I think the Tag model can be the same as the Environment model. Using UUID for the ID and the name is just a display name (could be updated, or could be duplicated). Of course, the same display name is not good and we can do a loose check to avoid using the same name when a new tag is created or updated but after all, users have to ensure that uniqueness.

**Comment by nghialv** [comment]
I think it would be nice if in the future this "Tag" model can also be used to replace our Environment model. The Environment is just a sub-set of Tag functionality since promoting features seems to not depend on that Environment.

Btw, I am still considering which is better "Label" or "Tag". (Tag could be a Label with empty key)
(Sorry for bringing the old topic to this again but it came up to me after thinking about removing the Environment model in the future. 🤣 )

**Comment by nakabonne** [comment]
@nghialv 

>Of course, the same display name is not good and we can do a loose check to avoid using the same name when a new tag is created or updated but after all, users have to ensure that uniqueness.

Yeah, if you think about it, when you create/update tags, you need to query the Datastore for the number of tags with the specified name, but if you limit the number of tags, this will work fine.

One thing that I was worried about is the time when disabling tags. Keeping uniqueness with disabled tags will confuse us.
But this can also be simplified by using `deleted` instead of `disabled`, so that it cannot be restored once a tag is deleted.

> this "Tag" model can also be used to replace our Environment model. The Environment is just a sub-set of Tag functionality

Agree with it.

>Sorry for bringing the old topic to this again

No, it's definitely worth considering. In the case of replacement Environment, using Labe (key: value) isn't bad. Let me think more about it.

**Comment by nakabonne** [comment]
We settled on defining them in the application configuration so now we don't have to pay attention to this suggestion stuff on the web.

For labeling I opened a new issue https://github.com/pipe-cd/pipe/issues/2750, so let me close this.
/close
