### ISSUE TITLE
` failed to append logs ` error on CLOUDRUN_PROMOTE step when deploying cloudrun services

### ISSUE THREAD

**Issue by yliu-d** [pipe-cd/pipe#2722]
**What happened**: For all deployments, CLOUDRUN_PROMOTE step has no log, other non-cloudrun steps have log. Piped log contains following pattern:
```
failed to report stage logs from last checkpoint	{"key": {"DeploymentID":"d9df5ce0-5b0b-495a-ae65-01ab4acdde04","StageID":"stage-0"}, "error": "rpc error: code = Internal desc = failed to append logs"}
github.com/pipe-cd/pipe/pkg/app/piped/logpersister.(*persister).reportStageLogsFromLastCheckpoint
	pkg/app/piped/logpersister/persister.go:198
github.com/pipe-cd/pipe/pkg/app/piped/logpersister.(*stageLogPersister).flushFromLastCheckpoint
	pkg/app/piped/logpersister/stagelogpersister.go:198
github.com/pipe-cd/pipe/pkg/app/piped/logpersister.(*stageLogPersister).flush
	pkg/app/piped/logpersister/stagelogpersister.go:155
github.com/pipe-cd/pipe/pkg/app/piped/logpersister.(*persister).flush.func1
	pkg/app/piped/logpersister/persister.go:145
sync.(*Map).Range
	GOROOT/src/sync/map.go:345
github.com/pipe-cd/pipe/pkg/app/piped/logpersister.(*persister).flush
	pkg/app/piped/logpersister/persister.go:136
github.com/pipe-cd/pipe/pkg/app/piped/logpersister.(*persister).Run
	pkg/app/piped/logpersister/persister.go:93
github.com/pipe-cd/pipe/pkg/app/piped/controller.(*controller).Run.func1
	pkg/app/piped/controller/controller.go:220
```

**What you expected to happen**: piped should push all logs to pipecd

**How to reproduce it**:

1. install pipecd
2. install piped with invalid gcp service account
3. add application, attempt deployment and fail
4. upgrade piped with correct gcp service account
5. observe logging issue on `CLOUDRUN_PROMOTE` step

**Environment**:
- `piped` version: v0.21.0
- `control-plane` version: v0.21.0
- Others: GCP service account permissions: (I'm using the same service account for both control plane and piped)
  Cloud Datastore Index Admin
  Cloud Datastore User
  Cloud Run Admin
  Service Account User

**Comment by nghialv** [comment]
@yliu-d Hi, Thank you for your report.

You are right. Our this [doc](https://pipecd.dev/docs/operator-manual/control-plane/installation/) is bad. 
In the case of using GCS 

https://pipecd.dev/docs/operator-manual/control-plane/installation/#using-firestore-and-gcs

the `gcs-service-account` needs `roles/storage.objectAdmin` role to be able to write log file to GCS bucket.

I have updated our doc (https://github.com/pipe-cd/pipe/pull/2723) and hope that adding will work for you.
Thanks.
