### ISSUE TITLE
Avoid database from receiving a lot of AppConfig updates when Piped is starting up 

### ISSUE THREAD

**Issue by nghialv** [pipe-cd/pipe#2838]
**What would you like to be added**:

Currently, Piped is sending the AppConfig of all applications to the control plane while starting up.
https://github.com/pipe-cd/pipe/blob/master/pkg/app/piped/appconfigreporter/appconfigreporter.go#L210-L248

Then it spawns a lot of requests to the database to update all applications.
This will be not good for large projects where they have hundreds to thousands of applications.
https://github.com/pipe-cd/pipe/blob/master/pkg/app/api/grpcapi/piped_api.go#L981-L992

So the idea to resolve that problem is sending only changed ones even for the first time while starting up.
For the existing application, that can be done easily by checking with the current config fields in the application model since Piped has all of its application data.

Based on that idea, we also can simplify the `findRegisteredApps` function
https://github.com/pipe-cd/pipe/blob/master/pkg/app/piped/appconfigreporter/appconfigreporter.go#L209-L278

to be something like this for all the cases:
```
func findUpdatedApps() {
- iterate application list
- for each application
    - load app config
    - check if there is any update by comparing with the field in the application model
}
```

This way also brings another good point is that it always ensures data in the database is synced eventually with the state defined in Git after each iteration, even if someone tried to update some field via the web console or API.

Btw, we can close #2837 issue once this got resolved.

**Why is this needed**:

**Comment by nakabonne** [comment]
That makes more sense 👍
