### ISSUE TITLE
Update the default value of configuration file name in Add Application form

### ISSUE THREAD

**Issue by nghialv** [pipe-cd/pipe#2931]
**What would you like to be added**:

Although we still allow using `.pipe.yaml`, I think it should just be used as the default value internally and we should slowly push users to switch to the new name with `.pipecd.yaml` extension for all new applications.

So how about using `application.pipecd.yaml` as the default value for the config file name file in the form below:

![Screen Shot 2021-12-13 at 14 00 08](https://user-images.githubusercontent.com/1751755/145755128-2f596932-5d4c-436f-ba7b-54b568610e8a.png)

**Why is this needed**:

**Comment by nakabonne** [comment]
Looks nice!

**Comment by nakabonne** [comment]
@khanhtc1202 It's nice to change the default name to `application.pipecd.yaml` for me. But what do you think? If it's fine to you as well, let me do it right now.

**Comment by khanhtc1202** [comment]
Well, I can say that the name `application.pipecd.yaml` is too long for me, and a shorter name like `.pipecd.yaml` could be better, but I don't have a strong opinion on that 😅

**Comment by nakabonne** [comment]
I feel you, that being sai, `.pipecd.yaml` has slightly different meaning. What we suggest is just using name suffixed by `.pipecd.yaml`.
It supposed to be like `dev.pipecd.yaml`, `prod.pipecd.yaml` and so on. We want to avoid handling the file as a hidden file.
So how about app.pipecd.yaml?

**Comment by khanhtc1202** [comment]
yeh, I just think about `app.pipecd.yaml` too, let's go with that option 👍

**Comment by nakabonne** [comment]
Alright!
