### ISSUE TITLE
doc: Missing  img `quickstart-adding-environment.png`

### ISSUE THREAD

**Issue by utamori** [pipe-cd/pipe#2968]
**What happened**:

The image specified in the following section of the documentation site appears to be missing

https://pipecd.dev/docs/quickstart/#3-adding-an-environment

![image](https://user-images.githubusercontent.com/59682979/146847583-5b689708-8170-4390-b7a5-26a1b0e1641e.png)

**Comment by nghialv** [comment]
@utamori Thanks for your report.

You are right!

I have just re-added that missing screenshot and it will be shown once the pull request got merged.
https://github.com/pipe-cd/pipe/pull/2969
