### ISSUE TITLE
It seems the copy button in Generate API key dialog does not work

### ISSUE THREAD

**Issue by nghialv** [pipe-cd/pipe#2976]
**What happened**:

The key was not copied when clicking the copy button.

**What you expected to happen**:

![Screen Shot 2021-12-21 at 18 30 41](https://user-images.githubusercontent.com/1751755/146906135-3439756a-a177-4cff-933e-518cd61027bc.png)

**How to reproduce it**:

**Environment**:
- `piped` version:
- `control-plane` version:
- Others:

**Comment by nakabonne** [comment]
I can't repro it. It seems to be able to copy it normally at least in our dev (v0.22.0-75-g14d9373) cluster.

**Comment by nghialv** [comment]
You are right!
It worked on our dev environment but didn't work for my quickstart environment.

**Comment by khanhtc1202** [comment]
> I can't repro it. It seems to be able to copy it normally at least in our dev (v0.22.0-75-g14d9373) cluster.

Me either, just tested in my local with latest codebase 👀

**Comment by nghialv** [comment]
Yep, got this when clicking on the button.

```
333.730d21ea9.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'writeText')
    at main.890ffae8f.js:1
    at Object.Ve (333.730d21ea9.js:2)
    at Ye (333.730d21ea9.js:2)
    at 333.730d21ea9.js:2
    at wr (333.730d21ea9.js:2)
    at Tr (333.730d21ea9.js:2)
    at 333.730d21ea9.js:2
    at je (333.730d21ea9.js:2)
    at 333.730d21ea9.js:2
```

**Comment by khanhtc1202** [comment]
Thanks, lets me check it 🙆‍♀️

**Comment by nghialv** [comment]
Thank you.

**Comment by khanhtc1202** [comment]
sadly but I tried run-up a PipeCD control-plane follow `quickstart` guide, but can not reproduce your issue 😢

**Comment by nghialv** [comment]
Looks like it was just a random bug.
Rechecked it on a new quickstart environment and it worked normally.
/close
