### ISSUE TITLE
Show traffic routing percentage on K8S_TRAFFIC_ROUTING stage

### ISSUE THREAD

**Issue by nghialv** [pipe-cd/pipe#459]
**What would you like to be added**:

"Approved by user" と同じく、 `K8S_TRAFFIC_ROUTING` stageで以下のようなmetadataを保存している（保存していない場合もある）

```
primary-percentage: 80
canary-percentage: 20
baseline-percentage: 0
```

**Why is this needed**:

/assign @cakecatz 
/label area/web

**Comment by cakecatz** [comment]
@nghialv I created UIs for it.

1.
![image](https://user-images.githubusercontent.com/6136383/97662537-b8b45f80-1aba-11eb-97e5-e505004997d7.png)

---

2.
![image](https://user-images.githubusercontent.com/6136383/97662548-c10c9a80-1aba-11eb-92cb-7f6e4cdb4ab9.png)

This UI has title attributes, so if you hover this stage, show details like this.
![image](https://user-images.githubusercontent.com/6136383/97662553-c4078b00-1aba-11eb-8fd7-61ab3e7f10e5.png)

---

Which one do you think is better?
If you have any other ideas, I'd like to hear them.
