### ISSUE TITLE
Use tagged k8s.io/* packages

### ISSUE THREAD

**Issue by dulltz** [pipe-cd/pipe#923]
**What would you like to be added**:

Currently, this repository manages the k8s.io/* package with a commit hash specification,
but in this way, it's hard to tell which version of k8s.io package is used.

- https://github.com/pipe-cd/pipe/blob/b9c9799899be14fe0f4a8af8341b8fa7b7814c7d/go.mod#L40-L42
- https://github.com/pipe-cd/pipe/blob/b9c9799899be14fe0f4a8af8341b8fa7b7814c7d/go.mod#L46-L50

There is a straightforward way to manage k8s.io packages with tags.
- https://github.com/kubernetes/client-go/blob/becbabb360023e1825a48b4db85f454e452ae249/INSTALL.md#add-client-go-as-a-dependency

like this:

```diff
--- a/go.mod
+++ b/go.mod
@@ -37,14 +37,8 @@ require (
        google.golang.org/grpc v1.31.1
        google.golang.org/protobuf v1.25.0
        istio.io/api v0.0.0-20200710191538-00b73d23c685
-       k8s.io/api v0.0.0-20200410021914-5778e4f3d00d
-       k8s.io/apimachinery v0.18.1
-       k8s.io/client-go v0.0.0-20200410022504-7b0589a2468d
+       k8s.io/api v0.18.2
+       k8s.io/apimachinery v0.18.2
+       k8s.io/client-go v0.18.2
        sigs.k8s.io/yaml v1.2.0
 )
-
-replace (
-       k8s.io/api => k8s.io/api v0.0.0-20200410021914-5778e4f3d00d
-       k8s.io/apimachinery => k8s.io/apimachinery v0.0.0-20200410021338-ff54c5b023af
-       k8s.io/client-go => k8s.io/client-go v0.0.0-20200410022504-7b0589a2468d
-)
```

**Why is this needed**:

To make it easier to know which version is used.

**Comment by nghialv** [comment]
@dulltz Thank you for a nice suggestion. You're absolutely right.
The PR #924 will update them.
