### ISSUE TITLE
Simplify the diff message for sensitive data

### ISSUE THREAD

**Issue by nakabonne** [pipe-cd/pipe#930]
**What would you like to be added**:
I'd say `secret-data-in-git` and `secret-data-in-cluster` could confuse some people. Why not just use `****` or something like that?

![image](https://user-images.githubusercontent.com/19730728/95317003-835b8e00-08cf-11eb-8568-d424e144de11.png)

**Why is this needed**:

**Comment by nghialv** [comment]
"***" is good. Can you update them?
